import { Page } from "@clutchd/layout";
import { Analytics } from "@vercel/analytics/react";
import { Manrope } from "next/font/google";
import { cookies } from 'next/headers';
import { DarkModeToggle } from "../components";
import React from "react";
import "./globals.css";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const theme = cookieStore.get('theme');
  return (
    <html lang="en" className={manrope.variable}>
      <body className={theme?.value === "dark" && "dark"}>
        <Page className="p-6 bg-white">
          <DarkModeToggle initialValue={theme?.value as ('light' | 'dark')} />
          {children}
          <Analytics />
        </Page>
      </body>
    </html>
  );
}
