export { Bold } from "./bold";
export type { IBold, IBoldProps } from "./bold";
export { Caption } from "./caption";
export type { ICaption, ICaptionProps } from "./caption";
export { Heading } from "./heading";
export type { IHeading, IHeadingProps } from "./heading";
export { Italic } from "./italic";
export type { IItalic, IItalicProps } from "./italic";
export { Subtitle } from "./subtitle";
export type { ISubtitle, ISubtitleProps } from "./subtitle";
export { Text } from "./text";
export type { IText, ITextProps } from "./text";
export { Title } from "./title";
export type { ITitle, ITitleProps } from "./title";
