import { fromTheme } from "./from-theme";
import {
  isAny,
  isArbitraryLength,
  isArbitraryNumber,
  isArbitraryPosition,
  isArbitraryShadow,
  isArbitrarySize,
  isArbitraryUrl,
  isArbitraryValue,
  isInteger,
  isLength,
  isTshirtSize,
} from "./validators";

export function getDefaultConfig() {
  const colors = fromTheme("colors");
  const spacing = fromTheme("spacing");
  const blur = fromTheme("blur");
  const brightness = fromTheme("brightness");
  const borderColor = fromTheme("borderColor");
  const borderRadius = fromTheme("borderRadius");
  const borderSpacing = fromTheme("borderSpacing");
  const borderWidth = fromTheme("borderWidth");
  const contrast = fromTheme("contrast");
  const grayscale = fromTheme("grayscale");
  const hueRotate = fromTheme("hueRotate");
  const invert = fromTheme("invert");
  const gap = fromTheme("gap");
  const gradientColorStops = fromTheme("gradientColorStops");
  const inset = fromTheme("inset");
  const margin = fromTheme("margin");
  const opacity = fromTheme("opacity");
  const padding = fromTheme("padding");
  const saturate = fromTheme("saturate");
  const scale = fromTheme("scale");
  const sepia = fromTheme("sepia");
  const skew = fromTheme("skew");
  const space = fromTheme("space");
  const translate = fromTheme("translate");

  const getOverscroll = () => ["auto", "contain", "none"] as const;
  const getOverflow = () =>
    ["auto", "hidden", "clip", "visible", "scroll"] as const;
  const getSpacingWithAuto = () => ["auto", spacing] as const;
  const getLengthWithEmpty = () => ["", isLength] as const;
  const getIntegerWithAuto = () => ["auto", isInteger] as const;
  const getPositions = () =>
    [
      "bottom",
      "center",
      "left",
      "left-bottom",
      "left-top",
      "right",
      "right-bottom",
      "right-top",
      "top",
    ] as const;
  const getLineStyles = () =>
    ["solid", "dashed", "dotted", "double", "none"] as const;
  const getBlendModes = () =>
    [
      "normal",
      "multiply",
      "screen",
      "overlay",
      "darken",
      "lighten",
      "color-dodge",
      "color-burn",
      "hard-light",
      "soft-light",
      "difference",
      "exclusion",
      "hue",
      "saturation",
      "color",
      "luminosity",
      "plus-lighter",
    ] as const;
  const getAlign = () =>
    ["start", "end", "center", "between", "around", "evenly"] as const;
  const getZeroAndEmpty = () => ["", "0", isArbitraryValue] as const;
  const getBreaks = () =>
    [
      "auto",
      "avoid",
      "all",
      "avoid-page",
      "page",
      "left",
      "right",
      "column",
    ] as const;

  return {
    theme: {
      colors: [isAny],
      spacing: [isLength],
      blur: ["none", "", isTshirtSize, isArbitraryLength],
      brightness: [isInteger],
      borderColor: [colors],
      borderRadius: ["none", "", "full", isTshirtSize, isArbitraryLength],
      borderSpacing: [spacing],
      borderWidth: getLengthWithEmpty(),
      contrast: [isInteger],
      grayscale: getZeroAndEmpty(),
      hueRotate: [isInteger],
      invert: getZeroAndEmpty(),
      gap: [spacing],
      gradientColorStops: [colors],
      inset: getSpacingWithAuto(),
      margin: getSpacingWithAuto(),
      opacity: [isInteger],
      padding: [spacing],
      saturate: [isInteger],
      scale: [isInteger],
      sepia: getZeroAndEmpty(),
      skew: [isInteger, isArbitraryValue],
      space: [spacing],
      translate: [spacing],
    },
    classGroups: {
      aspect: [{ aspect: ["auto", "square", "video", isArbitraryValue] }],
      container: ["container"],
      columns: [{ columns: [isTshirtSize] }],
      "break-after": [{ "break-after": getBreaks() }],
      "break-before": [{ "break-before": getBreaks() }],
      "break-inside": [
        { "break-inside": ["auto", "avoid", "avoid-page", "avoid-column"] },
      ],
      "box-decoration": [{ "box-decoration": ["slice", "clone"] }],
      box: [{ box: ["border", "content"] }],
      display: [
        "block",
        "inline-block",
        "inline",
        "flex",
        "inline-flex",
        "table",
        "inline-table",
        "table-caption",
        "table-cell",
        "table-column",
        "table-column-group",
        "table-footer-group",
        "table-header-group",
        "table-row-group",
        "table-row",
        "flow-root",
        "grid",
        "inline-grid",
        "contents",
        "list-item",
        "hidden",
      ],
      float: [{ float: ["right", "left", "none"] }],
      clear: [{ clear: ["left", "right", "both", "none"] }],
      isolation: ["isolate", "isolation-auto"],
      "object-fit": [
        { object: ["contain", "cover", "fill", "none", "scale-down"] },
      ],
      "object-position": [{ object: [...getPositions(), isArbitraryValue] }],
      overflow: [{ overflow: getOverflow() }],
      "overflow-x": [{ "overflow-x": getOverflow() }],
      "overflow-y": [{ "overflow-y": getOverflow() }],
      overscroll: [{ overscroll: getOverscroll() }],
      "overscroll-x": [{ "overscroll-x": getOverscroll() }],
      "overscroll-y": [{ "overscroll-y": getOverscroll() }],
      position: ["static", "fixed", "absolute", "relative", "sticky"],
      inset: [{ inset: [inset] }],
      "inset-x": [{ "inset-x": [inset] }],
      "inset-y": [{ "inset-y": [inset] }],
      top: [{ top: [inset] }],
      right: [{ right: [inset] }],
      bottom: [{ bottom: [inset] }],
      left: [{ left: [inset] }],
      visibility: ["visible", "invisible", "collapse"],
      z: [{ z: [isInteger] }],
      basis: [{ basis: [spacing] }],
      "flex-direction": [
        { flex: ["row", "row-reverse", "col", "col-reverse"] },
      ],
      "flex-wrap": [{ flex: ["wrap", "wrap-reverse", "nowrap"] }],
      flex: [{ flex: ["1", "auto", "initial", "none", isArbitraryValue] }],
      grow: [{ grow: getZeroAndEmpty() }],
      shrink: [{ shrink: getZeroAndEmpty() }],
      order: [{ order: ["first", "last", "none", isInteger] }],
      "grid-cols": [{ "grid-cols": [isAny] }],
      "col-start-end": [{ col: ["auto", { span: [isInteger] }] }],
      "col-start": [{ "col-start": getIntegerWithAuto() }],
      "col-end": [{ "col-end": getIntegerWithAuto() }],
      "grid-rows": [{ "grid-rows": [isAny] }],
      "row-start-end": [{ row: ["auto", { span: [isInteger] }] }],
      "row-start": [{ "row-start": getIntegerWithAuto() }],
      "row-end": [{ "row-end": getIntegerWithAuto() }],
      "grid-flow": [
        { "grid-flow": ["row", "col", "dense", "row-dense", "col-dense"] },
      ],
      "auto-cols": [
        { "auto-cols": ["auto", "min", "max", "fr", isArbitraryValue] },
      ],
      "auto-rows": [
        { "auto-rows": ["auto", "min", "max", "fr", isArbitraryValue] },
      ],
      gap: [{ gap: [gap] }],
      "gap-x": [{ "gap-x": [gap] }],
      "gap-y": [{ "gap-y": [gap] }],
      "justify-content": [{ justify: getAlign() }],
      "justify-items": [
        { "justify-items": ["start", "end", "center", "stretch"] },
      ],
      "justify-self": [
        { "justify-self": ["auto", "start", "end", "center", "stretch"] },
      ],
      "align-content": [{ content: [...getAlign(), "baseline"] }],
      "align-items": [
        { items: ["start", "end", "center", "baseline", "stretch"] },
      ],
      "align-self": [
        { self: ["auto", "start", "end", "center", "stretch", "baseline"] },
      ],
      "place-content": [
        { "place-content": [...getAlign(), "baseline", "stretch"] },
      ],
      "place-items": [
        { "place-items": ["start", "end", "center", "baseline", "stretch"] },
      ],
      "place-self": [
        { "place-self": ["auto", "start", "end", "center", "stretch"] },
      ],
      p: [{ p: [padding] }],
      px: [{ px: [padding] }],
      py: [{ py: [padding] }],
      pt: [{ pt: [padding] }],
      pr: [{ pr: [padding] }],
      pb: [{ pb: [padding] }],
      pl: [{ pl: [padding] }],
      m: [{ m: [margin] }],
      mx: [{ mx: [margin] }],
      my: [{ my: [margin] }],
      mt: [{ mt: [margin] }],
      mr: [{ mr: [margin] }],
      mb: [{ mb: [margin] }],
      ml: [{ ml: [margin] }],
      "space-x": [{ "space-x": [space] }],
      "space-x-reverse": ["space-x-reverse"],
      "space-y": [{ "space-y": [space] }],
      "space-y-reverse": ["space-y-reverse"],
      w: [{ w: ["auto", "min", "max", "fit", spacing] }],
      "min-w": [{ "min-w": ["min", "max", "fit", isLength] }],
      "max-w": [
        {
          "max-w": [
            "0",
            "none",
            "full",
            "min",
            "max",
            "fit",
            "prose",
            { screen: [isTshirtSize] },
            isTshirtSize,
            isArbitraryLength,
          ],
        },
      ],
      h: [{ h: [spacing, "auto", "min", "max", "fit"] }],
      "min-h": [{ "min-h": ["min", "max", "fit", isLength] }],
      "max-h": [{ "max-h": [spacing, "min", "max", "fit"] }],
      "font-size": [{ text: ["base", isTshirtSize, isArbitraryLength] }],
      "font-smoothing": ["antialiased", "subpixel-antialiased"],
      "font-style": ["italic", "not-italic"],
      "font-weight": [
        {
          font: [
            "thin",
            "extralight",
            "light",
            "normal",
            "medium",
            "semibold",
            "bold",
            "extrabold",
            "black",
            isArbitraryNumber,
          ],
        },
      ],
      "font-family": [{ font: [isAny] }],
      "fvn-normal": ["normal-nums"],
      "fvn-ordinal": ["ordinal"],
      "fvn-slashed-zero": ["slashed-zero"],
      "fvn-figure": ["lining-nums", "oldstyle-nums"],
      "fvn-spacing": ["proportional-nums", "tabular-nums"],
      "fvn-fraction": ["diagonal-fractions", "stacked-fractons"],
      tracking: [
        {
          tracking: [
            "tighter",
            "tight",
            "normal",
            "wide",
            "wider",
            "widest",
            isArbitraryLength,
          ],
        },
      ],
      leading: [
        {
          leading: [
            "none",
            "tight",
            "snug",
            "normal",
            "relaxed",
            "loose",
            isLength,
          ],
        },
      ],
      "list-style-type": [
        { list: ["none", "disc", "decimal", isArbitraryValue] },
      ],
      "list-style-position": [{ list: ["inside", "outside"] }],
      "placeholder-color": [{ placeholder: [colors] }],
      "placeholder-opacity": [{ "placeholder-opacity": [opacity] }],
      "text-alignment": [
        { text: ["left", "center", "right", "justify", "start", "end"] },
      ],
      "text-color": [{ text: [colors] }],
      "text-opacity": [{ "text-opacity": [opacity] }],
      "text-decoration": [
        "underline",
        "overline",
        "line-through",
        "no-underline",
      ],
      "text-decoration-style": [{ decoration: [...getLineStyles(), "wavy"] }],
      "text-decoration-thickness": [
        { decoration: ["auto", "from-font", isLength] },
      ],
      "underline-offset": [{ "underline-offset": ["auto", isLength] }],
      "text-decoration-color": [{ decoration: [colors] }],
      "text-transform": ["uppercase", "lowercase", "capitalize", "normal-case"],
      "text-overflow": ["truncate", "text-ellipsis", "text-clip"],
      indent: [{ indent: [spacing] }],
      "vertical-align": [
        {
          align: [
            "baseline",
            "top",
            "middle",
            "bottom",
            "text-top",
            "text-bottom",
            "sub",
            "super",
            isArbitraryLength,
          ],
        },
      ],
      whitespace: [
        { whitespace: ["normal", "nowrap", "pre", "pre-line", "pre-wrap"] },
      ],
      break: [{ break: ["normal", "words", "all", "keep"] }],
      content: [{ content: ["none", isArbitraryValue] }],
      "bg-attachment": [{ bg: ["fixed", "local", "scroll"] }],
      "bg-clip": [{ "bg-clip": ["border", "padding", "content", "text"] }],
      "bg-opacity": [{ "bg-opacity": [opacity] }],
      "bg-origin": [{ "bg-origin": ["border", "padding", "content"] }],
      "bg-position": [{ bg: [...getPositions(), isArbitraryPosition] }],
      "bg-repeat": [
        { bg: ["no-repeat", { repeat: ["", "x", "y", "round", "space"] }] },
      ],
      "bg-size": [{ bg: ["auto", "cover", "contain", isArbitrarySize] }],
      "bg-image": [
        {
          bg: [
            "none",
            { "gradient-to": ["t", "tr", "r", "br", "b", "bl", "l", "tl"] },
            isArbitraryUrl,
          ],
        },
      ],
      "bg-color": [{ bg: [colors] }],
      "gradient-from": [{ from: [gradientColorStops] }],
      "gradient-via": [{ via: [gradientColorStops] }],
      "gradient-to": [{ to: [gradientColorStops] }],
      rounded: [{ rounded: [borderRadius] }],
      "rounded-t": [{ "rounded-t": [borderRadius] }],
      "rounded-r": [{ "rounded-r": [borderRadius] }],
      "rounded-b": [{ "rounded-b": [borderRadius] }],
      "rounded-l": [{ "rounded-l": [borderRadius] }],
      "rounded-tl": [{ "rounded-tl": [borderRadius] }],
      "rounded-tr": [{ "rounded-tr": [borderRadius] }],
      "rounded-br": [{ "rounded-br": [borderRadius] }],
      "rounded-bl": [{ "rounded-bl": [borderRadius] }],
      "border-w": [{ border: [borderWidth] }],
      "border-w-x": [{ "border-x": [borderWidth] }],
      "border-w-y": [{ "border-y": [borderWidth] }],
      "border-w-t": [{ "border-t": [borderWidth] }],
      "border-w-r": [{ "border-r": [borderWidth] }],
      "border-w-b": [{ "border-b": [borderWidth] }],
      "border-w-l": [{ "border-l": [borderWidth] }],
      "border-opacity": [{ "border-opacity": [opacity] }],
      "border-style": [{ border: [...getLineStyles(), "hidden"] }],
      "divide-x": [{ "divide-x": [borderWidth] }],
      "divide-x-reverse": ["divide-x-reverse"],
      "divide-y": [{ "divide-y": [borderWidth] }],
      "divide-y-reverse": ["divide-y-reverse"],
      "divide-opacity": [{ "divide-opacity": [opacity] }],
      "divide-style": [{ divide: getLineStyles() }],
      "border-color": [{ border: [borderColor] }],
      "border-color-x": [{ "border-x": [borderColor] }],
      "border-color-y": [{ "border-y": [borderColor] }],
      "border-color-t": [{ "border-t": [borderColor] }],
      "border-color-r": [{ "border-r": [borderColor] }],
      "border-color-b": [{ "border-b": [borderColor] }],
      "border-color-l": [{ "border-l": [borderColor] }],
      "divide-color": [{ divide: [borderColor] }],
      "outline-style": [{ outline: ["", ...getLineStyles()] }],
      "outline-offset": [{ "outline-offset": [isLength] }],
      "outline-w": [{ outline: [isLength] }],
      "outline-color": [{ outline: [colors] }],
      "ring-w": [{ ring: getLengthWithEmpty() }],
      "ring-w-inset": ["ring-inset"],
      "ring-color": [{ ring: [colors] }],
      "ring-opacity": [{ "ring-opacity": [opacity] }],
      "ring-offset-w": [{ "ring-offset": [isLength] }],
      "ring-offset-color": [{ "ring-offset": [colors] }],
      shadow: [
        { shadow: ["", "inner", "none", isTshirtSize, isArbitraryShadow] },
      ],
      "shadow-color": [{ shadow: [isAny] }],
      opacity: [{ opacity: [opacity] }],
      "mix-blend": [{ "mix-blend": getBlendModes() }],
      "bg-blend": [{ "bg-blend": getBlendModes() }],
      filter: [{ filter: ["", "none"] }],
      blur: [{ blur: [blur] }],
      brightness: [{ brightness: [brightness] }],
      contrast: [{ contrast: [contrast] }],
      "drop-shadow": [
        { "drop-shadow": ["", "none", isTshirtSize, isArbitraryValue] },
      ],
      grayscale: [{ grayscale: [grayscale] }],
      "hue-rotate": [{ "hue-rotate": [hueRotate] }],
      invert: [{ invert: [invert] }],
      saturate: [{ saturate: [saturate] }],
      sepia: [{ sepia: [sepia] }],
      "backdrop-filter": [{ "backdrop-filter": ["", "none"] }],
      "backdrop-blur": [{ "backdrop-blur": [blur] }],
      "backdrop-brightness": [{ "backdrop-brightness": [brightness] }],
      "backdrop-contrast": [{ "backdrop-contrast": [contrast] }],
      "backdrop-grayscale": [{ "backdrop-grayscale": [grayscale] }],
      "backdrop-hue-rotate": [{ "backdrop-hue-rotate": [hueRotate] }],
      "backdrop-invert": [{ "backdrop-invert": [invert] }],
      "backdrop-opacity": [{ "backdrop-opacity": [opacity] }],
      "backdrop-saturate": [{ "backdrop-saturate": [saturate] }],
      "backdrop-sepia": [{ "backdrop-sepia": [sepia] }],
      "border-collapse": [{ border: ["collapse", "separate"] }],
      "border-spacing": [{ "border-spacing": [borderSpacing] }],
      "border-spacing-x": [{ "border-spacing-x": [borderSpacing] }],
      "border-spacing-y": [{ "border-spacing-y": [borderSpacing] }],
      "table-layout": [{ table: ["auto", "fixed"] }],
      transition: [
        {
          transition: [
            "none",
            "all",
            "",
            "colors",
            "opacity",
            "shadow",
            "transform",
            isArbitraryValue,
          ],
        },
      ],
      duration: [{ duration: [isInteger] }],
      ease: [{ ease: ["linear", "in", "out", "in-out", isArbitraryValue] }],
      delay: [{ delay: [isInteger] }],
      animate: [
        {
          animate: [
            "none",
            "spin",
            "ping",
            "pulse",
            "bounce",
            isArbitraryValue,
          ],
        },
      ],
      transform: [{ transform: ["", "gpu", "none"] }],
      scale: [{ scale: [scale] }],
      "scale-x": [{ "scale-x": [scale] }],
      "scale-y": [{ "scale-y": [scale] }],
      rotate: [{ rotate: [isInteger, isArbitraryValue] }],
      "translate-x": [{ "translate-x": [translate] }],
      "translate-y": [{ "translate-y": [translate] }],
      "skew-x": [{ "skew-x": [skew] }],
      "skew-y": [{ "skew-y": [skew] }],
      "transform-origin": [
        {
          origin: [
            "center",
            "top",
            "top-right",
            "right",
            "bottom-right",
            "bottom",
            "bottom-left",
            "left",
            "top-left",
            isArbitraryValue,
          ],
        },
      ],
      accent: [{ accent: ["auto", colors] }],
      appearance: ["appearance-none"],
      cursor: [
        {
          cursor: [
            "auto",
            "default",
            "pointer",
            "wait",
            "text",
            "move",
            "help",
            "not-allowed",
            "none",
            "context-menu",
            "progress",
            "cell",
            "crosshair",
            "vertical-text",
            "alias",
            "copy",
            "no-drop",
            "grab",
            "grabbing",
            "all-scroll",
            "col-resize",
            "row-resize",
            "n-resize",
            "e-resize",
            "s-resize",
            "w-resize",
            "ne-resize",
            "nw-resize",
            "se-resize",
            "sw-resize",
            "ew-resize",
            "ns-resize",
            "nesw-resize",
            "nwse-resize",
            "zoom-in",
            "zoom-out",
            isArbitraryValue,
          ],
        },
      ],
      "caret-color": [{ caret: [colors] }],
      "pointer-events": [{ "pointer-events": ["none", "auto"] }],
      resize: [{ resize: ["none", "y", "x", ""] }],
      "scroll-behavior": [{ scroll: ["auto", "smooth"] }],
      "scroll-m": [{ "scroll-m": [spacing] }],
      "scroll-mx": [{ "scroll-mx": [spacing] }],
      "scroll-my": [{ "scroll-my": [spacing] }],
      "scroll-mt": [{ "scroll-mt": [spacing] }],
      "scroll-mr": [{ "scroll-mr": [spacing] }],
      "scroll-mb": [{ "scroll-mb": [spacing] }],
      "scroll-ml": [{ "scroll-ml": [spacing] }],
      "scroll-p": [{ "scroll-p": [spacing] }],
      "scroll-px": [{ "scroll-px": [spacing] }],
      "scroll-py": [{ "scroll-py": [spacing] }],
      "scroll-pt": [{ "scroll-pt": [spacing] }],
      "scroll-pr": [{ "scroll-pr": [spacing] }],
      "scroll-pb": [{ "scroll-pb": [spacing] }],
      "scroll-pl": [{ "scroll-pl": [spacing] }],
      "snap-align": [{ snap: ["start", "end", "center", "align-none"] }],
      "snap-stop": [{ snap: ["normal", "always"] }],
      "snap-type": [{ snap: ["none", "x", "y", "both"] }],
      "snap-strictness": [{ snap: ["mandatory", "proximity"] }],
      touch: [
        {
          touch: [
            "auto",
            "none",
            "pinch-zoom",
            "manipulation",
            { pan: ["x", "left", "right", "y", "up", "down"] },
          ],
        },
      ],
      select: [{ select: ["none", "text", "all", "auto"] }],
      "will-change": [
        {
          "will-change": [
            "auto",
            "scroll",
            "contents",
            "transform",
            isArbitraryValue,
          ],
        },
      ],
      fill: [{ fill: [colors, "none"] }],
      "stroke-w": [{ stroke: [isLength, isArbitraryNumber] }],
      stroke: [{ stroke: [colors, "none"] }],
      sr: ["sr-only", "not-sr-only"],
    },
    conflictingClassGroups: {
      overflow: ["overflow-x", "overflow-y"],
      overscroll: ["overscroll-x", "overscroll-y"],
      inset: ["inset-x", "inset-y", "top", "right", "bottom", "left"],
      "inset-x": ["right", "left"],
      "inset-y": ["top", "bottom"],
      flex: ["basis", "grow", "shrink"],
      gap: ["gap-x", "gap-y"],
      p: ["px", "py", "pt", "pr", "pb", "pl"],
      px: ["pr", "pl"],
      py: ["pt", "pb"],
      m: ["mx", "my", "mt", "mr", "mb", "ml"],
      mx: ["mr", "ml"],
      my: ["mt", "mb"],
      "font-size": ["leading"],
      "fvn-normal": [
        "fvn-ordinal",
        "fvn-slashed-zero",
        "fvn-figure",
        "fvn-spacing",
        "fvn-fraction",
      ],
      "fvn-ordinal": ["fvn-normal"],
      "fvn-slashed-zero": ["fvn-normal"],
      "fvn-figure": ["fvn-normal"],
      "fvn-spacing": ["fvn-normal"],
      "fvn-fraction": ["fvn-normal"],
      rounded: [
        "rounded-t",
        "rounded-r",
        "rounded-b",
        "rounded-l",
        "rounded-tl",
        "rounded-tr",
        "rounded-br",
        "rounded-bl",
      ],
      "rounded-t": ["rounded-tl", "rounded-tr"],
      "rounded-r": ["rounded-tr", "rounded-br"],
      "rounded-b": ["rounded-br", "rounded-bl"],
      "rounded-l": ["rounded-tl", "rounded-bl"],
      "border-spacing": ["border-spacing-x", "border-spacing-y"],
      "border-w": ["border-w-t", "border-w-r", "border-w-b", "border-w-l"],
      "border-w-x": ["border-w-r", "border-w-l"],
      "border-w-y": ["border-w-t", "border-w-b"],
      "border-color": [
        "border-color-t",
        "border-color-r",
        "border-color-b",
        "border-color-l",
      ],
      "border-color-x": ["border-color-r", "border-color-l"],
      "border-color-y": ["border-color-t", "border-color-b"],
      "scroll-m": [
        "scroll-mx",
        "scroll-my",
        "scroll-mt",
        "scroll-mr",
        "scroll-mb",
        "scroll-ml",
      ],
      "scroll-mx": ["scroll-mr", "scroll-ml"],
      "scroll-my": ["scroll-mt", "scroll-mb"],
      "scroll-p": [
        "scroll-px",
        "scroll-py",
        "scroll-pt",
        "scroll-pr",
        "scroll-pb",
        "scroll-pl",
      ],
      "scroll-px": ["scroll-pr", "scroll-pl"],
      "scroll-py": ["scroll-pt", "scroll-pb"],
    },
  } as const;
}
