import { Page } from "@clutchd/layout";
import { Analytics } from "@vercel/analytics/react";
import { Manrope } from "next/font/google";
import type React from "react";
import "./globals.css";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={manrope.variable}>
      <Page asChild className="bg-white">
        <body>
          {children}
          <Analytics />
        </body>
      </Page>
    </html>
  );
}
